// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dtssdk/model/message.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgID int32

const (
	MsgID_ConnectID               MsgID = 0
	MsgID_DisconnectID            MsgID = 1
	MsgID_GetDefenceZoneRequestID MsgID = 2
	MsgID_GetDefenceZoneReplyID   MsgID = 3
	MsgID_SetDeviceRequestID      MsgID = 4
	MsgID_SetDeviceReplyID        MsgID = 5
	MsgID_ZoneTempNotifyID        MsgID = 6
	MsgID_ZoneAlarmNotifyID       MsgID = 7
	MsgID_DeviceEventNotifyID     MsgID = 8
	MsgID_TempSignalNotifyID      MsgID = 9
	MsgID_GetDeviceIDRequestID    MsgID = 10
	MsgID_GetDeviceIDReplyID      MsgID = 11
	MsgID_CancelSoundRequestID    MsgID = 12
	MsgID_CancelSoundReplyID      MsgID = 13
	MsgID_ResetAlarmRequestID     MsgID = 14
	MsgID_ResetAlarmReplyID       MsgID = 15
	MsgID_HeartBeatID             MsgID = 250
)

var MsgID_name = map[int32]string{
	0:   "ConnectID",
	1:   "DisconnectID",
	2:   "GetDefenceZoneRequestID",
	3:   "GetDefenceZoneReplyID",
	4:   "SetDeviceRequestID",
	5:   "SetDeviceReplyID",
	6:   "ZoneTempNotifyID",
	7:   "ZoneAlarmNotifyID",
	8:   "DeviceEventNotifyID",
	9:   "TempSignalNotifyID",
	10:  "GetDeviceIDRequestID",
	11:  "GetDeviceIDReplyID",
	12:  "CancelSoundRequestID",
	13:  "CancelSoundReplyID",
	14:  "ResetAlarmRequestID",
	15:  "ResetAlarmReplyID",
	250: "HeartBeatID",
}

var MsgID_value = map[string]int32{
	"ConnectID":               0,
	"DisconnectID":            1,
	"GetDefenceZoneRequestID": 2,
	"GetDefenceZoneReplyID":   3,
	"SetDeviceRequestID":      4,
	"SetDeviceReplyID":        5,
	"ZoneTempNotifyID":        6,
	"ZoneAlarmNotifyID":       7,
	"DeviceEventNotifyID":     8,
	"TempSignalNotifyID":      9,
	"GetDeviceIDRequestID":    10,
	"GetDeviceIDReplyID":      11,
	"CancelSoundRequestID":    12,
	"CancelSoundReplyID":      13,
	"ResetAlarmRequestID":     14,
	"ResetAlarmReplyID":       15,
	"HeartBeatID":             250,
}

func (x MsgID) String() string {
	return proto.EnumName(MsgID_name, int32(x))
}

func (MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{0}
}

//防区状态
type DefenceAreaState int32

const (
	DefenceAreaState_Normal      DefenceAreaState = 0
	DefenceAreaState_WarnDiffer  DefenceAreaState = 1
	DefenceAreaState_WarnUp      DefenceAreaState = 2
	DefenceAreaState_WarnTemp    DefenceAreaState = 3
	DefenceAreaState_AlarmDiffer DefenceAreaState = 4
	DefenceAreaState_AlarmUp     DefenceAreaState = 5
	DefenceAreaState_AlarmTemp   DefenceAreaState = 6
)

var DefenceAreaState_name = map[int32]string{
	0: "Normal",
	1: "WarnDiffer",
	2: "WarnUp",
	3: "WarnTemp",
	4: "AlarmDiffer",
	5: "AlarmUp",
	6: "AlarmTemp",
}

var DefenceAreaState_value = map[string]int32{
	"Normal":      0,
	"WarnDiffer":  1,
	"WarnUp":      2,
	"WarnTemp":    3,
	"AlarmDiffer": 4,
	"AlarmUp":     5,
	"AlarmTemp":   6,
}

func (x DefenceAreaState) String() string {
	return proto.EnumName(DefenceAreaState_name, int32(x))
}

func (DefenceAreaState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{1}
}

//防区状态
type FiberState int32

const (
	FiberState_SSTATEISOK   FiberState = 0
	FiberState_SSTATUSUNFIN FiberState = 1
	FiberState_SSTATUSFIN   FiberState = 2
	FiberState_SSTATUSBRK   FiberState = 3
	FiberState_SSTATUSTLO   FiberState = 4
	FiberState_SSTATUSLTM   FiberState = 5
)

var FiberState_name = map[int32]string{
	0: "SSTATEISOK",
	1: "SSTATUSUNFIN",
	2: "SSTATUSFIN",
	3: "SSTATUSBRK",
	4: "SSTATUSTLO",
	5: "SSTATUSLTM",
}

var FiberState_value = map[string]int32{
	"SSTATEISOK":   0,
	"SSTATUSUNFIN": 1,
	"SSTATUSFIN":   2,
	"SSTATUSBRK":   3,
	"SSTATUSTLO":   4,
	"SSTATUSLTM":   5,
}

func (x FiberState) String() string {
	return proto.EnumName(FiberState_name, int32(x))
}

func (FiberState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{2}
}

//设备
type DeviceEvent struct {
	ChannelID            int32      `protobuf:"varint,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	DeviceID             string     `protobuf:"bytes,2,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Timestamp            int64      `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	EventType            FiberState `protobuf:"varint,4,opt,name=EventType,proto3,enum=model.FiberState" json:"EventType,omitempty"`
	ChannelLength        float32    `protobuf:"fixed32,5,opt,name=ChannelLength,proto3" json:"ChannelLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeviceEvent) Reset()         { *m = DeviceEvent{} }
func (m *DeviceEvent) String() string { return proto.CompactTextString(m) }
func (*DeviceEvent) ProtoMessage()    {}
func (*DeviceEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{0}
}

func (m *DeviceEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEvent.Unmarshal(m, b)
}
func (m *DeviceEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEvent.Marshal(b, m, deterministic)
}
func (m *DeviceEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEvent.Merge(m, src)
}
func (m *DeviceEvent) XXX_Size() int {
	return xxx_messageInfo_DeviceEvent.Size(m)
}
func (m *DeviceEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEvent proto.InternalMessageInfo

func (m *DeviceEvent) GetChannelID() int32 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *DeviceEvent) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *DeviceEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DeviceEvent) GetEventType() FiberState {
	if m != nil {
		return m.EventType
	}
	return FiberState_SSTATEISOK
}

func (m *DeviceEvent) GetChannelLength() float32 {
	if m != nil {
		return m.ChannelLength
	}
	return 0
}

//防区
type DefenceZone struct {
	ID                   int32            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ChannelID            int32            `protobuf:"varint,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	ZoneName             string           `protobuf:"bytes,3,opt,name=ZoneName,proto3" json:"ZoneName,omitempty"`
	Start                float32          `protobuf:"fixed32,4,opt,name=Start,proto3" json:"Start,omitempty"`
	Finish               float32          `protobuf:"fixed32,5,opt,name=Finish,proto3" json:"Finish,omitempty"`
	Tag                  string           `protobuf:"bytes,6,opt,name=Tag,proto3" json:"Tag,omitempty"`
	AlarmType            DefenceAreaState `protobuf:"varint,7,opt,name=AlarmType,proto3,enum=model.DefenceAreaState" json:"AlarmType,omitempty"`
	AlarmLoc             float32          `protobuf:"fixed32,8,opt,name=AlarmLoc,proto3" json:"AlarmLoc,omitempty"`
	MaxTemperature       float32          `protobuf:"fixed32,9,opt,name=MaxTemperature,proto3" json:"MaxTemperature,omitempty"`
	MinTemperature       float32          `protobuf:"fixed32,10,opt,name=MinTemperature,proto3" json:"MinTemperature,omitempty"`
	AverageTemperature   float32          `protobuf:"fixed32,11,opt,name=AverageTemperature,proto3" json:"AverageTemperature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DefenceZone) Reset()         { *m = DefenceZone{} }
func (m *DefenceZone) String() string { return proto.CompactTextString(m) }
func (*DefenceZone) ProtoMessage()    {}
func (*DefenceZone) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{1}
}

func (m *DefenceZone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefenceZone.Unmarshal(m, b)
}
func (m *DefenceZone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefenceZone.Marshal(b, m, deterministic)
}
func (m *DefenceZone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefenceZone.Merge(m, src)
}
func (m *DefenceZone) XXX_Size() int {
	return xxx_messageInfo_DefenceZone.Size(m)
}
func (m *DefenceZone) XXX_DiscardUnknown() {
	xxx_messageInfo_DefenceZone.DiscardUnknown(m)
}

var xxx_messageInfo_DefenceZone proto.InternalMessageInfo

func (m *DefenceZone) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DefenceZone) GetChannelID() int32 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *DefenceZone) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *DefenceZone) GetStart() float32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *DefenceZone) GetFinish() float32 {
	if m != nil {
		return m.Finish
	}
	return 0
}

func (m *DefenceZone) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *DefenceZone) GetAlarmType() DefenceAreaState {
	if m != nil {
		return m.AlarmType
	}
	return DefenceAreaState_Normal
}

func (m *DefenceZone) GetAlarmLoc() float32 {
	if m != nil {
		return m.AlarmLoc
	}
	return 0
}

func (m *DefenceZone) GetMaxTemperature() float32 {
	if m != nil {
		return m.MaxTemperature
	}
	return 0
}

func (m *DefenceZone) GetMinTemperature() float32 {
	if m != nil {
		return m.MinTemperature
	}
	return 0
}

func (m *DefenceZone) GetAverageTemperature() float32 {
	if m != nil {
		return m.AverageTemperature
	}
	return 0
}

//设置设备请求
type SetDeviceRequest struct {
	ZoneTempNotifyEnable    bool     `protobuf:"varint,1,opt,name=ZoneTempNotifyEnable,proto3" json:"ZoneTempNotifyEnable,omitempty"`
	ZoneAlarmNotifyEnable   bool     `protobuf:"varint,2,opt,name=ZoneAlarmNotifyEnable,proto3" json:"ZoneAlarmNotifyEnable,omitempty"`
	FiberStatusNotifyEnable bool     `protobuf:"varint,3,opt,name=FiberStatusNotifyEnable,proto3" json:"FiberStatusNotifyEnable,omitempty"`
	TempSignalNotifyEnable  bool     `protobuf:"varint,4,opt,name=TempSignalNotifyEnable,proto3" json:"TempSignalNotifyEnable,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *SetDeviceRequest) Reset()         { *m = SetDeviceRequest{} }
func (m *SetDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*SetDeviceRequest) ProtoMessage()    {}
func (*SetDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{2}
}

func (m *SetDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceRequest.Unmarshal(m, b)
}
func (m *SetDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceRequest.Marshal(b, m, deterministic)
}
func (m *SetDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceRequest.Merge(m, src)
}
func (m *SetDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_SetDeviceRequest.Size(m)
}
func (m *SetDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceRequest proto.InternalMessageInfo

func (m *SetDeviceRequest) GetZoneTempNotifyEnable() bool {
	if m != nil {
		return m.ZoneTempNotifyEnable
	}
	return false
}

func (m *SetDeviceRequest) GetZoneAlarmNotifyEnable() bool {
	if m != nil {
		return m.ZoneAlarmNotifyEnable
	}
	return false
}

func (m *SetDeviceRequest) GetFiberStatusNotifyEnable() bool {
	if m != nil {
		return m.FiberStatusNotifyEnable
	}
	return false
}

func (m *SetDeviceRequest) GetTempSignalNotifyEnable() bool {
	if m != nil {
		return m.TempSignalNotifyEnable
	}
	return false
}

//设置设备回执
type SetDeviceReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDeviceReply) Reset()         { *m = SetDeviceReply{} }
func (m *SetDeviceReply) String() string { return proto.CompactTextString(m) }
func (*SetDeviceReply) ProtoMessage()    {}
func (*SetDeviceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{3}
}

func (m *SetDeviceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceReply.Unmarshal(m, b)
}
func (m *SetDeviceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceReply.Marshal(b, m, deterministic)
}
func (m *SetDeviceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceReply.Merge(m, src)
}
func (m *SetDeviceReply) XXX_Size() int {
	return xxx_messageInfo_SetDeviceReply.Size(m)
}
func (m *SetDeviceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceReply proto.InternalMessageInfo

func (m *SetDeviceReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SetDeviceReply) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

//获取所有防区
type GetDefenceZoneRequest struct {
	Channel              int32    `protobuf:"varint,1,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Search               string   `protobuf:"bytes,2,opt,name=Search,proto3" json:"Search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDefenceZoneRequest) Reset()         { *m = GetDefenceZoneRequest{} }
func (m *GetDefenceZoneRequest) String() string { return proto.CompactTextString(m) }
func (*GetDefenceZoneRequest) ProtoMessage()    {}
func (*GetDefenceZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{4}
}

func (m *GetDefenceZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDefenceZoneRequest.Unmarshal(m, b)
}
func (m *GetDefenceZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDefenceZoneRequest.Marshal(b, m, deterministic)
}
func (m *GetDefenceZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDefenceZoneRequest.Merge(m, src)
}
func (m *GetDefenceZoneRequest) XXX_Size() int {
	return xxx_messageInfo_GetDefenceZoneRequest.Size(m)
}
func (m *GetDefenceZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDefenceZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDefenceZoneRequest proto.InternalMessageInfo

func (m *GetDefenceZoneRequest) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *GetDefenceZoneRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

//获取所有防区
type GetDefenceZoneReply struct {
	Success              bool           `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	ErrMsg               string         `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Rows                 []*DefenceZone `protobuf:"bytes,3,rep,name=Rows,proto3" json:"Rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetDefenceZoneReply) Reset()         { *m = GetDefenceZoneReply{} }
func (m *GetDefenceZoneReply) String() string { return proto.CompactTextString(m) }
func (*GetDefenceZoneReply) ProtoMessage()    {}
func (*GetDefenceZoneReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{5}
}

func (m *GetDefenceZoneReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDefenceZoneReply.Unmarshal(m, b)
}
func (m *GetDefenceZoneReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDefenceZoneReply.Marshal(b, m, deterministic)
}
func (m *GetDefenceZoneReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDefenceZoneReply.Merge(m, src)
}
func (m *GetDefenceZoneReply) XXX_Size() int {
	return xxx_messageInfo_GetDefenceZoneReply.Size(m)
}
func (m *GetDefenceZoneReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDefenceZoneReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDefenceZoneReply proto.InternalMessageInfo

func (m *GetDefenceZoneReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetDefenceZoneReply) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetDefenceZoneReply) GetRows() []*DefenceZone {
	if m != nil {
		return m.Rows
	}
	return nil
}

//获取设备id 请求
type GetDeviceIDRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceIDRequest) Reset()         { *m = GetDeviceIDRequest{} }
func (m *GetDeviceIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceIDRequest) ProtoMessage()    {}
func (*GetDeviceIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{6}
}

func (m *GetDeviceIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceIDRequest.Unmarshal(m, b)
}
func (m *GetDeviceIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceIDRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceIDRequest.Merge(m, src)
}
func (m *GetDeviceIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceIDRequest.Size(m)
}
func (m *GetDeviceIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceIDRequest proto.InternalMessageInfo

//获取设备id 回执
type GetDeviceIDReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	DeviceID             string   `protobuf:"bytes,3,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceIDReply) Reset()         { *m = GetDeviceIDReply{} }
func (m *GetDeviceIDReply) String() string { return proto.CompactTextString(m) }
func (*GetDeviceIDReply) ProtoMessage()    {}
func (*GetDeviceIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{7}
}

func (m *GetDeviceIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceIDReply.Unmarshal(m, b)
}
func (m *GetDeviceIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceIDReply.Marshal(b, m, deterministic)
}
func (m *GetDeviceIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceIDReply.Merge(m, src)
}
func (m *GetDeviceIDReply) XXX_Size() int {
	return xxx_messageInfo_GetDeviceIDReply.Size(m)
}
func (m *GetDeviceIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceIDReply proto.InternalMessageInfo

func (m *GetDeviceIDReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetDeviceIDReply) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetDeviceIDReply) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

//消音请求
type CancelSoundRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelSoundRequest) Reset()         { *m = CancelSoundRequest{} }
func (m *CancelSoundRequest) String() string { return proto.CompactTextString(m) }
func (*CancelSoundRequest) ProtoMessage()    {}
func (*CancelSoundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{8}
}

func (m *CancelSoundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelSoundRequest.Unmarshal(m, b)
}
func (m *CancelSoundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelSoundRequest.Marshal(b, m, deterministic)
}
func (m *CancelSoundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelSoundRequest.Merge(m, src)
}
func (m *CancelSoundRequest) XXX_Size() int {
	return xxx_messageInfo_CancelSoundRequest.Size(m)
}
func (m *CancelSoundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelSoundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelSoundRequest proto.InternalMessageInfo

//消音回执
type CancelSoundReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelSoundReply) Reset()         { *m = CancelSoundReply{} }
func (m *CancelSoundReply) String() string { return proto.CompactTextString(m) }
func (*CancelSoundReply) ProtoMessage()    {}
func (*CancelSoundReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{9}
}

func (m *CancelSoundReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelSoundReply.Unmarshal(m, b)
}
func (m *CancelSoundReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelSoundReply.Marshal(b, m, deterministic)
}
func (m *CancelSoundReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelSoundReply.Merge(m, src)
}
func (m *CancelSoundReply) XXX_Size() int {
	return xxx_messageInfo_CancelSoundReply.Size(m)
}
func (m *CancelSoundReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelSoundReply.DiscardUnknown(m)
}

var xxx_messageInfo_CancelSoundReply proto.InternalMessageInfo

func (m *CancelSoundReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CancelSoundReply) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

//重置警报请求
type ResetAlarmRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetAlarmRequest) Reset()         { *m = ResetAlarmRequest{} }
func (m *ResetAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*ResetAlarmRequest) ProtoMessage()    {}
func (*ResetAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{10}
}

func (m *ResetAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetAlarmRequest.Unmarshal(m, b)
}
func (m *ResetAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetAlarmRequest.Marshal(b, m, deterministic)
}
func (m *ResetAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetAlarmRequest.Merge(m, src)
}
func (m *ResetAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_ResetAlarmRequest.Size(m)
}
func (m *ResetAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetAlarmRequest proto.InternalMessageInfo

//重置警报回执
type ResetAlarmReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetAlarmReply) Reset()         { *m = ResetAlarmReply{} }
func (m *ResetAlarmReply) String() string { return proto.CompactTextString(m) }
func (*ResetAlarmReply) ProtoMessage()    {}
func (*ResetAlarmReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{11}
}

func (m *ResetAlarmReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetAlarmReply.Unmarshal(m, b)
}
func (m *ResetAlarmReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetAlarmReply.Marshal(b, m, deterministic)
}
func (m *ResetAlarmReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetAlarmReply.Merge(m, src)
}
func (m *ResetAlarmReply) XXX_Size() int {
	return xxx_messageInfo_ResetAlarmReply.Size(m)
}
func (m *ResetAlarmReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetAlarmReply.DiscardUnknown(m)
}

var xxx_messageInfo_ResetAlarmReply proto.InternalMessageInfo

func (m *ResetAlarmReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResetAlarmReply) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

//防区温度，广播
type ZoneTempNotify struct {
	DeviceID             string         `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Timestamp            int64          `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Zones                []*DefenceZone `protobuf:"bytes,3,rep,name=Zones,proto3" json:"Zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ZoneTempNotify) Reset()         { *m = ZoneTempNotify{} }
func (m *ZoneTempNotify) String() string { return proto.CompactTextString(m) }
func (*ZoneTempNotify) ProtoMessage()    {}
func (*ZoneTempNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{12}
}

func (m *ZoneTempNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneTempNotify.Unmarshal(m, b)
}
func (m *ZoneTempNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneTempNotify.Marshal(b, m, deterministic)
}
func (m *ZoneTempNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneTempNotify.Merge(m, src)
}
func (m *ZoneTempNotify) XXX_Size() int {
	return xxx_messageInfo_ZoneTempNotify.Size(m)
}
func (m *ZoneTempNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneTempNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneTempNotify proto.InternalMessageInfo

func (m *ZoneTempNotify) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *ZoneTempNotify) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ZoneTempNotify) GetZones() []*DefenceZone {
	if m != nil {
		return m.Zones
	}
	return nil
}

//防区警报 广播
type ZoneAlarmNotify struct {
	DeviceID             string         `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Timestamp            int64          `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Zones                []*DefenceZone `protobuf:"bytes,3,rep,name=Zones,proto3" json:"Zones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ZoneAlarmNotify) Reset()         { *m = ZoneAlarmNotify{} }
func (m *ZoneAlarmNotify) String() string { return proto.CompactTextString(m) }
func (*ZoneAlarmNotify) ProtoMessage()    {}
func (*ZoneAlarmNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{13}
}

func (m *ZoneAlarmNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneAlarmNotify.Unmarshal(m, b)
}
func (m *ZoneAlarmNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneAlarmNotify.Marshal(b, m, deterministic)
}
func (m *ZoneAlarmNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneAlarmNotify.Merge(m, src)
}
func (m *ZoneAlarmNotify) XXX_Size() int {
	return xxx_messageInfo_ZoneAlarmNotify.Size(m)
}
func (m *ZoneAlarmNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneAlarmNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneAlarmNotify proto.InternalMessageInfo

func (m *ZoneAlarmNotify) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *ZoneAlarmNotify) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ZoneAlarmNotify) GetZones() []*DefenceZone {
	if m != nil {
		return m.Zones
	}
	return nil
}

//设备状态， 广播
type DeviceEventNotify struct {
	ChannelID            int32      `protobuf:"varint,1,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	DeviceID             string     `protobuf:"bytes,2,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Timestamp            int64      `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	EventType            FiberState `protobuf:"varint,4,opt,name=EventType,proto3,enum=model.FiberState" json:"EventType,omitempty"`
	ChannelLength        float32    `protobuf:"fixed32,5,opt,name=ChannelLength,proto3" json:"ChannelLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DeviceEventNotify) Reset()         { *m = DeviceEventNotify{} }
func (m *DeviceEventNotify) String() string { return proto.CompactTextString(m) }
func (*DeviceEventNotify) ProtoMessage()    {}
func (*DeviceEventNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{14}
}

func (m *DeviceEventNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEventNotify.Unmarshal(m, b)
}
func (m *DeviceEventNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEventNotify.Marshal(b, m, deterministic)
}
func (m *DeviceEventNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEventNotify.Merge(m, src)
}
func (m *DeviceEventNotify) XXX_Size() int {
	return xxx_messageInfo_DeviceEventNotify.Size(m)
}
func (m *DeviceEventNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEventNotify.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEventNotify proto.InternalMessageInfo

func (m *DeviceEventNotify) GetChannelID() int32 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *DeviceEventNotify) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *DeviceEventNotify) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DeviceEventNotify) GetEventType() FiberState {
	if m != nil {
		return m.EventType
	}
	return FiberState_SSTATEISOK
}

func (m *DeviceEventNotify) GetChannelLength() float32 {
	if m != nil {
		return m.ChannelLength
	}
	return 0
}

//温度信号， 广播
type TempSignalNotify struct {
	DeviceID             string    `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	ChannelID            int32     `protobuf:"varint,2,opt,name=ChannelID,proto3" json:"ChannelID,omitempty"`
	RealLength           float32   `protobuf:"fixed32,3,opt,name=RealLength,proto3" json:"RealLength,omitempty"`
	Signal               []float32 `protobuf:"fixed32,4,rep,packed,name=Signal,proto3" json:"Signal,omitempty"`
	Timestamp            int64     `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TempSignalNotify) Reset()         { *m = TempSignalNotify{} }
func (m *TempSignalNotify) String() string { return proto.CompactTextString(m) }
func (*TempSignalNotify) ProtoMessage()    {}
func (*TempSignalNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{15}
}

func (m *TempSignalNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TempSignalNotify.Unmarshal(m, b)
}
func (m *TempSignalNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TempSignalNotify.Marshal(b, m, deterministic)
}
func (m *TempSignalNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TempSignalNotify.Merge(m, src)
}
func (m *TempSignalNotify) XXX_Size() int {
	return xxx_messageInfo_TempSignalNotify.Size(m)
}
func (m *TempSignalNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_TempSignalNotify.DiscardUnknown(m)
}

var xxx_messageInfo_TempSignalNotify proto.InternalMessageInfo

func (m *TempSignalNotify) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *TempSignalNotify) GetChannelID() int32 {
	if m != nil {
		return m.ChannelID
	}
	return 0
}

func (m *TempSignalNotify) GetRealLength() float32 {
	if m != nil {
		return m.RealLength
	}
	return 0
}

func (m *TempSignalNotify) GetSignal() []float32 {
	if m != nil {
		return m.Signal
	}
	return nil
}

func (m *TempSignalNotify) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

//心跳
type HeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9e331ea920348e8, []int{16}
}

func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (m *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(m, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("model.MsgID", MsgID_name, MsgID_value)
	proto.RegisterEnum("model.DefenceAreaState", DefenceAreaState_name, DefenceAreaState_value)
	proto.RegisterEnum("model.FiberState", FiberState_name, FiberState_value)
	proto.RegisterType((*DeviceEvent)(nil), "model.DeviceEvent")
	proto.RegisterType((*DefenceZone)(nil), "model.DefenceZone")
	proto.RegisterType((*SetDeviceRequest)(nil), "model.SetDeviceRequest")
	proto.RegisterType((*SetDeviceReply)(nil), "model.SetDeviceReply")
	proto.RegisterType((*GetDefenceZoneRequest)(nil), "model.GetDefenceZoneRequest")
	proto.RegisterType((*GetDefenceZoneReply)(nil), "model.GetDefenceZoneReply")
	proto.RegisterType((*GetDeviceIDRequest)(nil), "model.GetDeviceIDRequest")
	proto.RegisterType((*GetDeviceIDReply)(nil), "model.GetDeviceIDReply")
	proto.RegisterType((*CancelSoundRequest)(nil), "model.CancelSoundRequest")
	proto.RegisterType((*CancelSoundReply)(nil), "model.CancelSoundReply")
	proto.RegisterType((*ResetAlarmRequest)(nil), "model.ResetAlarmRequest")
	proto.RegisterType((*ResetAlarmReply)(nil), "model.ResetAlarmReply")
	proto.RegisterType((*ZoneTempNotify)(nil), "model.ZoneTempNotify")
	proto.RegisterType((*ZoneAlarmNotify)(nil), "model.ZoneAlarmNotify")
	proto.RegisterType((*DeviceEventNotify)(nil), "model.DeviceEventNotify")
	proto.RegisterType((*TempSignalNotify)(nil), "model.TempSignalNotify")
	proto.RegisterType((*HeartBeat)(nil), "model.HeartBeat")
}

func init() { proto.RegisterFile("dtssdk/model/message.proto", fileDescriptor_b9e331ea920348e8) }

var fileDescriptor_b9e331ea920348e8 = []byte{
	// 945 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcd, 0x4e, 0xeb, 0x46,
	0x14, 0xbe, 0xb6, 0xe3, 0xfc, 0x9c, 0x40, 0x18, 0x0e, 0x01, 0xdc, 0xdb, 0xaa, 0x8a, 0xac, 0xea,
	0x2a, 0x62, 0x01, 0x12, 0xfd, 0x51, 0xb7, 0xc0, 0xc0, 0xed, 0xe8, 0x42, 0xae, 0x64, 0x27, 0xaa,
	0xd4, 0x55, 0x87, 0x30, 0x04, 0xab, 0x89, 0x9d, 0xda, 0x13, 0x5a, 0x5e, 0xa3, 0x8f, 0xd0, 0xe7,
	0xe8, 0xaa, 0x8f, 0xd3, 0x45, 0x1f, 0xa0, 0xab, 0x6a, 0xc6, 0x8e, 0x63, 0x3b, 0xb9, 0x54, 0x62,
	0x51, 0xe9, 0xee, 0xf2, 0x9d, 0xf9, 0xce, 0xcf, 0xe7, 0x73, 0xe6, 0x4c, 0xe0, 0xf5, 0x9d, 0x4c,
	0x92, 0xbb, 0x9f, 0x4e, 0x66, 0xd1, 0x9d, 0x98, 0x9e, 0xcc, 0x44, 0x92, 0xf0, 0x89, 0x38, 0x9e,
	0xc7, 0x91, 0x8c, 0xd0, 0xd6, 0x46, 0xf7, 0x0f, 0x03, 0xda, 0x54, 0x3c, 0x06, 0x63, 0x71, 0xf9,
	0x28, 0x42, 0x89, 0x9f, 0x41, 0xeb, 0xe2, 0x81, 0x87, 0xa1, 0x98, 0x32, 0xea, 0x18, 0x3d, 0xa3,
	0x6f, 0x7b, 0x2b, 0x03, 0xbe, 0x86, 0x66, 0x4a, 0x66, 0xd4, 0x31, 0x7b, 0x46, 0xbf, 0xe5, 0xe5,
	0x58, 0x79, 0x0e, 0x83, 0x99, 0x48, 0x24, 0x9f, 0xcd, 0x1d, 0xab, 0x67, 0xf4, 0x2d, 0x6f, 0x65,
	0xc0, 0x13, 0x68, 0xe9, 0x04, 0xc3, 0xa7, 0xb9, 0x70, 0x6a, 0x3d, 0xa3, 0xdf, 0x39, 0xdd, 0x3d,
	0xd6, 0x25, 0x1c, 0x5f, 0x05, 0xb7, 0x22, 0xf6, 0x25, 0x97, 0xc2, 0x5b, 0x71, 0xf0, 0x0b, 0xd8,
	0xce, 0xf2, 0x5e, 0x8b, 0x70, 0x22, 0x1f, 0x1c, 0xbb, 0x67, 0xf4, 0x4d, 0xaf, 0x6c, 0x74, 0xff,
	0x32, 0x55, 0xf9, 0xf7, 0x22, 0x1c, 0x8b, 0x1f, 0xa2, 0x50, 0x60, 0x07, 0xcc, 0xbc, 0x6e, 0x33,
	0x2d, 0x6a, 0x25, 0xc7, 0xdc, 0x20, 0x47, 0x79, 0x0d, 0xf8, 0x4c, 0xe8, 0x8a, 0x5b, 0x5e, 0x8e,
	0xb1, 0x0b, 0xb6, 0x2f, 0x79, 0x2c, 0x75, 0xb1, 0xa6, 0x97, 0x02, 0x3c, 0x80, 0xfa, 0x55, 0x10,
	0x06, 0xc9, 0xb2, 0x9c, 0x0c, 0x21, 0x01, 0x6b, 0xc8, 0x27, 0x4e, 0x5d, 0x07, 0x51, 0x3f, 0xf1,
	0x6b, 0x68, 0x9d, 0x4d, 0x79, 0x3c, 0xd3, 0x82, 0x1b, 0x5a, 0xf0, 0x61, 0x26, 0x38, 0x2b, 0xf8,
	0x2c, 0x16, 0x3c, 0x93, 0x9d, 0x33, 0x55, 0x49, 0x1a, 0x5c, 0x47, 0x63, 0xa7, 0xa9, 0x53, 0xe4,
	0x18, 0xdf, 0x40, 0xe7, 0x86, 0xff, 0x3a, 0x14, 0xb3, 0xb9, 0x88, 0xb9, 0x5c, 0xc4, 0xc2, 0x69,
	0x69, 0x46, 0xc5, 0xaa, 0x79, 0x41, 0x58, 0xe4, 0x41, 0xc6, 0x2b, 0x59, 0xf1, 0x18, 0xf0, 0xec,
	0x51, 0xc4, 0x7c, 0x22, 0x8a, 0xdc, 0xb6, 0xe6, 0x6e, 0x38, 0x71, 0xff, 0x36, 0x80, 0xf8, 0x42,
	0xa6, 0x1d, 0xf7, 0xc4, 0xcf, 0x0b, 0x91, 0x48, 0x3c, 0x85, 0xae, 0xfa, 0x66, 0x8a, 0x37, 0x88,
	0x64, 0x70, 0xff, 0x74, 0x19, 0xf2, 0xdb, 0xa9, 0xd0, 0x3d, 0x68, 0x7a, 0x1b, 0xcf, 0xf0, 0x2b,
	0xd8, 0x57, 0x76, 0x2d, 0xac, 0xe4, 0x64, 0x6a, 0xa7, 0xcd, 0x87, 0xf8, 0x2d, 0x1c, 0xe6, 0xa3,
	0xb2, 0x48, 0x4a, 0x7e, 0x96, 0xf6, 0xfb, 0xd0, 0x31, 0x7e, 0x03, 0x07, 0xaa, 0x06, 0x3f, 0x98,
	0x84, 0x7c, 0x5a, 0x72, 0xac, 0x69, 0xc7, 0x0f, 0x9c, 0xba, 0xe7, 0xd0, 0x29, 0xe8, 0x9d, 0x4f,
	0x9f, 0xd0, 0x81, 0x86, 0xbf, 0x18, 0x8f, 0x45, 0x92, 0x64, 0x02, 0x97, 0x50, 0x4d, 0xc6, 0x65,
	0x1c, 0xdf, 0x24, 0x93, 0xec, 0x62, 0x64, 0xc8, 0x65, 0xb0, 0xff, 0x56, 0xc5, 0xc8, 0x67, 0x74,
	0xf9, 0xe1, 0x1c, 0x68, 0x64, 0x93, 0x98, 0xcd, 0xeb, 0x12, 0xaa, 0x50, 0xbe, 0xe0, 0xf1, 0xf8,
	0x61, 0x19, 0x2a, 0x45, 0x6e, 0x04, 0x7b, 0xd5, 0x50, 0x2f, 0xaa, 0x09, 0xdf, 0x40, 0xcd, 0x8b,
	0x7e, 0x49, 0x1c, 0xab, 0x67, 0xf5, 0xdb, 0xa7, 0x58, 0x1e, 0x4b, 0x1d, 0x58, 0x9f, 0xbb, 0x5d,
	0xc0, 0xb7, 0x4b, 0xfd, 0x8c, 0x66, 0x85, 0xbb, 0x3f, 0x02, 0x29, 0x59, 0x5f, 0x56, 0x43, 0x71,
	0x95, 0x58, 0xe5, 0x55, 0xa2, 0xf2, 0x5e, 0xf0, 0x70, 0x2c, 0xa6, 0x7e, 0xb4, 0x08, 0xef, 0x96,
	0x79, 0x29, 0x90, 0x92, 0xf5, 0x65, 0xfd, 0xd8, 0x83, 0x5d, 0x4f, 0x24, 0x42, 0xea, 0xf9, 0x5a,
	0x86, 0xbe, 0x80, 0x9d, 0xa2, 0xf1, 0x65, 0x91, 0x25, 0x74, 0xca, 0xd3, 0x5e, 0xd2, 0x68, 0x3c,
	0xb7, 0x2e, 0xcd, 0xea, 0xba, 0xec, 0x83, 0xad, 0x62, 0x3d, 0xd7, 0xa2, 0x94, 0xe0, 0x2e, 0x60,
	0xa7, 0x72, 0x5d, 0xfe, 0x97, 0xb4, 0x7f, 0x1a, 0xb0, 0x5b, 0x78, 0x37, 0xb2, 0xcc, 0x1f, 0xd9,
	0xeb, 0xf1, 0xbb, 0x01, 0xa4, 0x7a, 0xf5, 0xff, 0xeb, 0xeb, 0x3d, 0xf3, 0x9c, 0x7c, 0x0e, 0xe0,
	0x09, 0xbe, 0xcc, 0x68, 0xe9, 0x8c, 0x05, 0x8b, 0xbe, 0xd7, 0x3a, 0x93, 0x53, 0xeb, 0x59, 0xea,
	0xf1, 0x48, 0x51, 0x59, 0xbb, 0x5d, 0xd1, 0xee, 0xb6, 0xa1, 0xf5, 0x9d, 0xe0, 0xb1, 0x3c, 0x17,
	0x5c, 0x1e, 0xfd, 0x66, 0x81, 0x7d, 0x93, 0x4c, 0x18, 0xc5, 0x6d, 0x68, 0x5d, 0x44, 0x61, 0x28,
	0xc6, 0x92, 0x51, 0xf2, 0x0a, 0x09, 0x6c, 0xd1, 0x20, 0x19, 0xe7, 0x16, 0x03, 0x3f, 0x85, 0xc3,
	0x8d, 0x8b, 0x87, 0x51, 0x62, 0xe2, 0x27, 0xeb, 0x5b, 0x69, 0x3e, 0x7d, 0x62, 0x94, 0x58, 0x78,
	0x00, 0x58, 0x5d, 0xf2, 0x8c, 0x92, 0x1a, 0x76, 0x4b, 0xcb, 0x3f, 0x65, 0xdb, 0xca, 0x5a, 0x1e,
	0x7a, 0x46, 0x49, 0x1d, 0xf7, 0x61, 0xb7, 0x32, 0x94, 0x8c, 0x92, 0x06, 0x1e, 0xc2, 0xde, 0xda,
	0xcc, 0x30, 0x4a, 0x9a, 0x2a, 0x67, 0xb5, 0x0f, 0x8c, 0x92, 0x16, 0x3a, 0xd0, 0x5d, 0x5f, 0x40,
	0x8c, 0x12, 0x50, 0x1e, 0xd5, 0x25, 0xc4, 0x28, 0x69, 0x2b, 0x8f, 0xf5, 0xd5, 0xc1, 0x28, 0xd9,
	0x52, 0x1e, 0xd5, 0xf5, 0xc1, 0x28, 0xd9, 0x56, 0x45, 0xad, 0x2d, 0x04, 0x46, 0x49, 0x47, 0x89,
	0xa8, 0x2c, 0x05, 0x46, 0xc9, 0x0e, 0x12, 0x68, 0xe7, 0xfd, 0x60, 0x94, 0xfc, 0x63, 0x1c, 0x2d,
	0x80, 0x54, 0x9f, 0x74, 0x04, 0xa8, 0x0f, 0xa2, 0x78, 0xc6, 0xa7, 0xe4, 0x15, 0x76, 0x00, 0xbe,
	0xe7, 0x71, 0x48, 0x83, 0xfb, 0x7b, 0x11, 0x13, 0x43, 0x9d, 0x29, 0x3c, 0x9a, 0x13, 0x13, 0xb7,
	0xa0, 0xa9, 0x7e, 0x2b, 0xf5, 0xc4, 0xc2, 0x1d, 0x68, 0xeb, 0x6c, 0x19, 0xb5, 0x86, 0x6d, 0x68,
	0x68, 0xc3, 0x68, 0x4e, 0x6c, 0xd5, 0xf2, 0xf4, 0x8f, 0x82, 0x22, 0xd7, 0x8f, 0x42, 0x80, 0xd5,
	0xf0, 0xab, 0x24, 0xbe, 0x3f, 0x3c, 0x1b, 0x5e, 0x32, 0xff, 0xfd, 0xbb, 0x74, 0x20, 0x34, 0x1e,
	0xf9, 0xa3, 0xc1, 0x15, 0x1b, 0x10, 0x23, 0x67, 0x8c, 0x7c, 0x85, 0xcd, 0x02, 0x3e, 0xf7, 0xde,
	0x11, 0xab, 0x80, 0x87, 0xd7, 0xef, 0x49, 0xad, 0x80, 0xaf, 0x87, 0x37, 0xc4, 0xbe, 0xad, 0xeb,
	0x3f, 0x8e, 0x5f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xe9, 0x32, 0x33, 0x56, 0x0a, 0x00,
	0x00,
}
